### ISSUE TITLE
DataGrid

### ISSUE THREAD

**Issue by virzak** [marb2000/XamlIslands#16]
I would love to replace an existing WPF datagrid which recently went [closed source](https://github.com/xceedsoftware/wpftoolkit/issues/1445) with [UWP DataGrid](https://github.com/windows-toolkit/WindowsCommunityToolkit/tree/master/Microsoft.Toolkit.Uwp.UI.Controls.DataGrid).

However I couldn't add it as xamlhost control since it is not part of Windows.UI.Xaml.Controls

Any chance of an example of DataGrid in WPF?

Thanks!

**Comment by marb2000** [comment]
You are right. UWP DataGrid is not part of the inbox controls and it won't be, because all the controls will live in WinUI library. For using DataGrid in a WPF app you should follow up these guidelines: https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/host-custom-control-with-xaml-islands
